### ISSUE TITLE
積算電力量計測値がたまに跳ねる

### ISSUE THREAD

**Issue by hoshinota** [tonasuzuki/GetSmartMeterData#4]
原因は313行目で積算電力量を計算している部分で、Unitが受信失敗していて0が返ってたケースです
私の環境では通常1が返ってくるため、0の場合は10倍の値となっています。
312行目のif条件へfUnit>0を入れたらよい気もしますがdictUnitへ0も定義されているので
コマンド結果を受け取っている、260行目あたりでtime outならExceptionを投げるでもいいような気もします
コマンドの内容まで見れていないので、これから調べたいと思いますが、アドバイスなどあればお願いします

**Comment by tonasuzuki** [comment]
ご指摘ありがとうございます。
ECHONET機器からデータを取得できなかった場合の処理を追記致しました。先ほど更新したソースで試して頂けますよう、お願いいたします。

**Comment by hoshinota** [comment]
ありがとうございます
正常に動作することを確認できました
これは通信環境がわるいんでしょうね
